/* School calendar data — events, months, school metadata. No UI or CSS. */
window.CALENDAR_DATA = {
  "school": {
    "academicYear": "2026/2027",
    "gradeLabelUk": "1-й Клас • Ліцей",
    "schoolName": "LXXVIII Liceum Ogólnokształcące im. Marii Pawlikowskiej-Jasnorzewskiej w Warszawie",
    "schoolShort": "LXXVIII LO w Warszawie",
    "icsCalendarName": "Шкільний Календар 2026/2027 (1-й клас LXXVIII LO)",
    "timezone": "Europe/Warsaw",
    "notesStorageKey": "lyceum_78_notes_1st_grade"
  },
  "months": [
    {
      "id": "sep-2026",
      "name": "Вересень 2026",
      "year": 2026,
      "month": 9,
      "nameGenitive": "Вересня 2026"
    },
    {
      "id": "oct-2026",
      "name": "Жовтень 2026",
      "year": 2026,
      "month": 10,
      "nameGenitive": "Жовтня 2026"
    },
    {
      "id": "nov-2026",
      "name": "Листопад 2026",
      "year": 2026,
      "month": 11,
      "nameGenitive": "Листопада 2026"
    },
    {
      "id": "dec-2026",
      "name": "Грудень 2026",
      "year": 2026,
      "month": 12,
      "nameGenitive": "Грудня 2026"
    },
    {
      "id": "jan-2027",
      "name": "Січень 2027",
      "year": 2027,
      "month": 1,
      "nameGenitive": "Січня 2027"
    },
    {
      "id": "feb-2027",
      "name": "Лютий 2027",
      "year": 2027,
      "month": 2,
      "nameGenitive": "Лютого 2027"
    },
    {
      "id": "mar-2027",
      "name": "Березень 2027",
      "year": 2027,
      "month": 3,
      "nameGenitive": "Березня 2027"
    },
    {
      "id": "apr-2027",
      "name": "Квітень 2027",
      "year": 2027,
      "month": 4,
      "nameGenitive": "Квітня 2027"
    },
    {
      "id": "may-2027",
      "name": "Травень 2027",
      "year": 2027,
      "month": 5,
      "nameGenitive": "Травня 2027"
    },
    {
      "id": "jun-2027",
      "name": "Червень 2027",
      "year": 2027,
      "month": 6,
      "nameGenitive": "Червня 2027"
    },
    {
      "id": "jul-2027",
      "name": "Липень 2027",
      "year": 2027,
      "month": 7,
      "nameGenitive": "Липня 2027"
    },
    {
      "id": "aug-2027",
      "name": "Серпень 2027",
      "year": 2027,
      "month": 8,
      "nameGenitive": "Серпня 2027"
    }
  ],
  "events": [
    {
      "id": "ev-sep-1",
      "date": "2026-09-01",
      "dateFormatted": "01.09.2026 (Вівторок)",
      "title": "Урочистий початок 2026/2027 навчального року 🔔",
      "titlePl": "Uroczyste rozpoczęcie roku szkolnego 2026/2027",
      "category": "start",
      "categoryName": "Початок навчання",
      "time": "09:00",
      "description": "Перший дзвоник, урочиста лінійка та знайомство з класним керівником і ліцеєм. Офіційний старт I півріччя.",
      "grade1Note": "Обов'язкова присутність у святковому одязі. Перший день для першокласників у ліцеї!",
      "location": "LXXVIII LO w Warszawie, ul. Anieli Krzywoń 3"
    },
    {
      "id": "ev-sep-8-meeting",
      "date": "2026-09-08",
      "dateFormatted": "08.09.2026 (Вівторок)",
      "title": "Батьківські збори 1-х класів із директором 👥",
      "titlePl": "Spotkanie z Dyrektorem (klasy I) i wychowawcami",
      "category": "meeting",
      "categoryName": "Батьківські збори",
      "time": "17:30",
      "description": "Перша офіційна установча зустріч батьків учнів 1-х класів з керівництвом ліцею та класними керівниками.",
      "grade1Note": "Критично важливі збори для батьків 1-х класів: організація навчання, правила ліцею, доступ до електронного щоденника Librus, виїзна інтеграція.",
      "location": "Актова зала / кабінети ліцею"
    },
    {
      "id": "ev-sep-8-council",
      "date": "2026-09-08",
      "dateFormatted": "08.09.2026 (Вівторок)",
      "title": "Організаційна педагогічна рада ліцею 📋",
      "titlePl": "Rada pedagogiczna organizacyjna",
      "category": "council",
      "categoryName": "Педагогічна рада",
      "time": "15:00",
      "description": "Затвердження плану педагогічного нагляду та організація навчального процесу на рік.",
      "grade1Note": "Педагогічна рада вчителів ліцею.",
      "location": "Учительська ліцею"
    },
    {
      "id": "ev-sep-trip",
      "date": "2026-09-21",
      "endDate": "2026-09-25",
      "dateFormatted": "21.09 – 25.09.2026",
      "title": "Осінній виїзний (екскурсійний) тиждень ліцею 🚌",
      "titlePl": "Jesienny tydzień wyjazdowy / wycieczkowy",
      "category": "trip",
      "categoryName": "Виїзди та екскурсії",
      "time": "Весь тиждень",
      "description": "Традиційний виїзний тиждень ліцею: екскурсії, навчально-пізнавальні поїздки, краєзнавчі маршрути та командні активності.",
      "grade1Note": "1-ші класи беруть участь у спеціально підготовлених адаптаційних та освітніх екскурсіях.",
      "location": "Виїзні маршрути"
    },
    {
      "id": "ev-oct-integ",
      "date": "2026-10-01",
      "endDate": "2026-10-02",
      "dateFormatted": "01.10 – 02.10.2026 (Четвер – П'ятниця)",
      "title": "Дні виїзної інтеграції перших класів 🎒🤝",
      "titlePl": "Dni integracji wyjazdowej klas pierwszych",
      "category": "integ",
      "categoryName": "Інтеграція 1-х класів",
      "time": "2 дні",
      "description": "Головна виїзна подія для новоприбулих учнів: тренінги на згуртування, знайомство, командоутворення, спортивні та творчі квести.",
      "grade1Note": "Подія СТОСУЄТЬСЯ ВИКЛЮЧНО 1-Х КЛАСІВ! Допомагає новачкам швидко подружитися та влитися в атмосферу ліцею.",
      "location": "Заміська інтеграційна база ліцею"
    },
    {
      "id": "ev-oct-14-den",
      "date": "2026-10-14",
      "dateFormatted": "14.10.2026 (Середа)",
      "title": "День національної освіти в Польщі (DEN) 💐",
      "titlePl": "Dzień Edukacji Narodowej",
      "category": "school",
      "categoryName": "Шкільне свято",
      "time": "Весь день",
      "description": "Урочистий день вчителів та всієї шкільної спільноти. Традиційно проводяться шкільні урочистості, посвята першокласників (ślubowanie) або святкові заходи.",
      "grade1Note": "Урочистий день у ліцеї.",
      "location": "LXXVIII LO"
    },
    {
      "id": "ev-nov-1-all-saints",
      "date": "2026-11-01",
      "dateFormatted": "01.11.2026 (Неділя)",
      "title": "День усіх святих 🛑",
      "titlePl": "Wszystkich Świętych",
      "category": "holiday",
      "categoryName": "Державне свято",
      "time": "Весь день",
      "description": "Офіційне державне свято та вихідний день у всій Польщі.",
      "grade1Note": "Вихідний день.",
      "location": "Польща"
    },
    {
      "id": "ev-nov-3-meeting",
      "date": "2026-11-03",
      "dateFormatted": "03.11.2026 (Вівторок)",
      "title": "Батьківські збори: перші результати навчання 👥",
      "titlePl": "Zebranie z rodzicami: informacja o postępach i wynikach",
      "category": "meeting",
      "categoryName": "Батьківські збори",
      "time": "17:30",
      "description": "Аналіз перших двох місяців навчання в ліцеї, поточні оцінки учнів, зауваження вчителів-предметників та рекомендації.",
      "grade1Note": "Важлива перевірка адаптації першокласників до навантаження в ліцеї.",
      "location": "Кабінети класних керівників"
    },
    {
      "id": "ev-nov-11-independence",
      "date": "2026-11-11",
      "dateFormatted": "11.11.2026 (Середа)",
      "title": "Національне свято незалежності Польщі 🇵🇱🛑",
      "titlePl": "Narodowe Święto Niepodległości",
      "category": "holiday",
      "categoryName": "Державне свято",
      "time": "Весь день",
      "description": "Державний вихідний день. Занять немає.",
      "grade1Note": "Офіційний вихідний день у ліцеї.",
      "location": "Польща"
    },
    {
      "id": "ev-dec-15-grade",
      "date": "2026-12-15",
      "dateFormatted": "До 15.12.2026 (Вівторок)",
      "title": "Повідомлення про загрозу незадовільних оцінок ⚠️",
      "titlePl": "Poinformowanie o zagrożeniach ocenami niedostatecznymi za I półrocze",
      "category": "grade",
      "categoryName": "Оцінювання",
      "time": "Дедлайн",
      "description": "Офіційне письмове сповіщення батьків про ризик отримання учнем незадовільної семестрової оцінки або незадовільної оцінки з поведінки.",
      "grade1Note": "Батькам необхідно перевірити електронний щоденник Librus та звернутися до вчителів у разі заборгованостей.",
      "location": "Librus / Ліцей"
    },
    {
      "id": "ev-dec-15-meeting",
      "date": "2026-12-15",
      "dateFormatted": "15.12.2026 (Вівторок)",
      "title": "Батьківські збори: попередження щодо оцінок 👥",
      "titlePl": "Zebranie z rodzicami: zagrożenia ocenami",
      "category": "meeting",
      "categoryName": "Батьківські збори",
      "time": "17:30",
      "description": "Очні консультації батьків з класними керівниками та вчителями щодо виправлення оцінок до кінця I семестру.",
      "grade1Note": "Можливість узгодити графік перездач та консультацій перед семестровою класифікацією.",
      "location": "Кабінети ліцею"
    },
    {
      "id": "ev-dec-21-off",
      "date": "2026-12-21",
      "endDate": "2026-12-22",
      "dateFormatted": "21.12 – 22.12.2026 (Понеділок – Вівторок)",
      "title": "Вільні від уроків дні (Директорські вихідні) 🛑",
      "titlePl": "Dodatkowe dni wolne od zajęć dydaktyczno-wychowawczych",
      "category": "off",
      "categoryName": "Вільні дні",
      "time": "2 дні",
      "description": "Додаткові вихідні дні, встановлені дирекцією ліцею перед різдвяними канікулами. Занять немає.",
      "grade1Note": "Учні 1-х класів відпочивають.",
      "location": "Ліцей"
    },
    {
      "id": "ev-dec-23-vacation",
      "date": "2026-12-23",
      "endDate": "2026-12-31",
      "dateFormatted": "23.12 – 31.12.2026",
      "title": "Зимова різдвяна святкова перерва 🎄❄️",
      "titlePl": "Zimowa przerwa świąteczna (Boże Narodzenie)",
      "category": "vacation",
      "categoryName": "Канікули",
      "time": "Святкові канікули",
      "description": "Різдвяні шкільні канікули. 24 грудня — Святвечір (Wigilia), 25–26 грудня — Різдво Христове (Boże Narodzenie), 31 грудня — Сильвестр.",
      "grade1Note": "Шкільні канікули для всіх учнів ліцею.",
      "location": "Польща"
    },
    {
      "id": "ev-jan-1-newyear",
      "date": "2027-01-01",
      "dateFormatted": "01.01.2027 (П'ятниця)",
      "title": "Новий Рік 2027! 🎆🛑",
      "titlePl": "Nowy Rok 2027",
      "category": "holiday",
      "categoryName": "Державне свято",
      "time": "Весь день",
      "description": "Державне свято та офіційний вихідний день.",
      "grade1Note": "Вихідний день.",
      "location": "Польща"
    },
    {
      "id": "ev-jan-4-off",
      "date": "2027-01-04",
      "endDate": "2027-01-05",
      "dateFormatted": "04.01 – 05.01.2027 (Понеділок – Вівторок)",
      "title": "Вільні від уроків дні (Директорські вихідні) 🛑",
      "titlePl": "Dodatkowe dni wolne od zajęć dydaktycznych",
      "category": "off",
      "categoryName": "Вільні дні",
      "time": "2 дні",
      "description": "Директорські вихідні між Новим Роком та Водохрещем/Трьома Королями. Уроки не проводяться.",
      "grade1Note": "Вихідні дні для 1-х класів.",
      "location": "Ліцей"
    },
    {
      "id": "ev-jan-6-kings",
      "date": "2027-01-06",
      "dateFormatted": "06.01.2027 (Середа)",
      "title": "Свято Трьох Королів (Богоявлення) 👑🛑",
      "titlePl": "Święto Trzech Króli (Objawienie Pańskie)",
      "category": "holiday",
      "categoryName": "Державне свято",
      "time": "Весь день",
      "description": "Державне свято та вихідний день у всій Польщі.",
      "grade1Note": "Вихідний день.",
      "location": "Польща"
    },
    {
      "id": "ev-jan-22-grade",
      "date": "2027-01-22",
      "dateFormatted": "До 22.01.2027 (П'ятниця)",
      "title": "Остаточне виставлення підсумкових оцінок за I півріччя 📝",
      "titlePl": "Ostateczne wystawienie ocen za I półrocze",
      "category": "grade",
      "categoryName": "Оцінювання",
      "time": "Дедлайн",
      "description": "Закриття семестрового журналу оцінок для 1-х та 2-х класів. Усі оцінки мають бути зафіксовані в системі.",
      "grade1Note": "Фіксація підсумкових семестрових балів першокласників.",
      "location": "Librus"
    },
    {
      "id": "ev-jan-26-council",
      "date": "2027-01-26",
      "dateFormatted": "26.01.2027 (Вівторок)",
      "title": "Класифікаційна педрада для 1-х і 2-х класів 📋",
      "titlePl": "Klasyfikacyjna rada pedagogiczna (klasy 1 i 2)",
      "category": "council",
      "categoryName": "Педагогічна рада",
      "time": "15:00",
      "description": "Затвердження результатів класифікації за I семестр учнів 1-х та 2-х класів.",
      "grade1Note": "Педагогічна рада ліцею.",
      "location": "Учительська"
    },
    {
      "id": "ev-jan-26-meeting",
      "date": "2027-01-26",
      "dateFormatted": "26.01.2027 (Вівторок)",
      "title": "Батьківські збори: підсумки I півріччя 👥",
      "titlePl": "Zebranie z rodzicami: wyniki klasyfikacji za I półrocze",
      "category": "meeting",
      "categoryName": "Батьківські збори",
      "time": "17:30",
      "description": "Оголошення підсумкових семестрових оцінок, аналіз успішності учнів 1-х класів за перше півріччя.",
      "grade1Note": "Ключові збори за підсумками першого півріччя ліцею.",
      "location": "Кабінети ліцею"
    },
    {
      "id": "ev-jan-29-endsem",
      "date": "2027-01-29",
      "dateFormatted": "29.01.2027 (П'ятниця)",
      "title": "Завершення занять I півріччя 🏁",
      "titlePl": "Koniec zajęć I półrocza",
      "category": "start",
      "categoryName": "Кінець семестру",
      "time": "Останній день семестру",
      "description": "Офіційне завершення навчальних занять у першому семестрі.",
      "grade1Note": "Завершення I семестру.",
      "location": "Ліцей"
    },
    {
      "id": "ev-feb-1-start2",
      "date": "2027-02-01",
      "dateFormatted": "01.02.2027 (Понеділок)",
      "title": "Офіційний початок II півріччя 🚀",
      "titlePl": "Początek II półrocza",
      "category": "start",
      "categoryName": "Початок семестру",
      "time": "Старт II півріччя",
      "description": "Офіційний старт навчального процесу другого півріччя (дидактичні заняття відновлюються після канікул 15 лютого).",
      "grade1Note": "Юридичний початок II семестру.",
      "location": "Ліцей"
    },
    {
      "id": "ev-feb-vacation",
      "date": "2027-02-01",
      "endDate": "2027-02-14",
      "dateFormatted": "01.02 – 14.02.2027",
      "title": "Зимові канікули (Ferie zimowe) ⛷️❄️",
      "titlePl": "Ferie zimowe (woj. mazowieckie)",
      "category": "vacation",
      "categoryName": "Канікули",
      "time": "2 повних тижні",
      "description": "Офіційні зимові канікули для шкіл Мазовецького воєводства (Варшава). 2 повні тижні відпочинку для учнів.",
      "grade1Note": "Уроки не проводяться. Відпочинок для всіх учнів 1-х класів.",
      "location": "Польща"
    },
    {
      "id": "ev-feb-15-resume",
      "date": "2027-02-15",
      "dateFormatted": "15.02.2027 (Понеділок)",
      "title": "Відновлення аудиторних занять 📚",
      "titlePl": "Wznowienie zajęć po feriach zimowych",
      "category": "start",
      "categoryName": "Навчання",
      "time": "08:00",
      "description": "Повернення учнів до занять за розкладом II півріччя після зимових канікул.",
      "grade1Note": "Перший навчальний день після зимових канікул.",
      "location": "Ліцей"
    },
    {
      "id": "ev-feb-16-council",
      "date": "2027-02-16",
      "dateFormatted": "16.02.2027 (Вівторок)",
      "title": "Підсумкова педагогічна рада за I півріччя 📋",
      "titlePl": "Podsumowująca rada pedagogiczna za I półrocze",
      "category": "council",
      "categoryName": "Педагогічна рада",
      "time": "15:00",
      "description": "Аналіз педагогічних та виховних результатів ліцею за перше півріччя.",
      "grade1Note": "Педрада вчителів.",
      "location": "Учительська"
    },
    {
      "id": "ev-mar-easter",
      "date": "2027-03-25",
      "endDate": "2027-03-30",
      "dateFormatted": "25.03 – 30.03.2027",
      "title": "Весняна великодня святкова перерва 🐣🌷",
      "titlePl": "Wiosenna przerwa świąteczna (Wielkanoc)",
      "category": "vacation",
      "categoryName": "Канікули",
      "time": "Святкові дні",
      "description": "Весняні великодні канікули. 28 березня — Великдень (Wielkanoc), 29 березня — Великодній понеділок (Poniedziałek Wielkanocny).",
      "grade1Note": "Шкільні великодні канікули. Занять немає.",
      "location": "Польща"
    },
    {
      "id": "ev-mar-31-resume",
      "date": "2027-03-31",
      "dateFormatted": "31.03.2027 (Середа)",
      "title": "Відновлення аудиторних занять після Великодня 📚",
      "titlePl": "Wznowienie zajęć dydaktycznych",
      "category": "start",
      "categoryName": "Навчання",
      "time": "08:00",
      "description": "Повернення до навчання після Великодніх свят.",
      "grade1Note": "Усі уроки за звичайним розкладом середи.",
      "location": "Ліцей"
    },
    {
      "id": "ev-apr-6-meeting",
      "date": "2027-04-06",
      "dateFormatted": "06.04.2027 (Вівторок)",
      "title": "Батьківські збори: поточна успішність у II семестрі 👥",
      "titlePl": "Zebranie z rodzicami: informacja o postępach w nauce (klasy 1, 2, 3)",
      "category": "meeting",
      "categoryName": "Батьківські збори",
      "time": "17:30",
      "description": "Зустріч батьків із класними керівниками: поточні весняні оцінки, відвідуваність та підготовка до річної атестації.",
      "grade1Note": "Батьківські збори для 1-х, 2-х та 3-х класів.",
      "location": "Кабінети ліцею"
    },
    {
      "id": "ev-apr-8-openday",
      "date": "2027-04-08",
      "dateFormatted": "08.04.2027 (Четвер)",
      "title": "День відкритих дверей у Ліцеї 🏫✨",
      "titlePl": "Dzień otwarty w LXXVIII LO",
      "category": "school",
      "categoryName": "Шкільний захід",
      "time": "17:00",
      "description": "Презентація ліцею для майбутніх абітурієнтів. Першокласники часто беруть участь у презентації своїх профілів та напрямів.",
      "grade1Note": "Захід ліцею.",
      "location": "LXXVIII LO"
    },
    {
      "id": "ev-apr-trip",
      "date": "2027-04-26",
      "endDate": "2027-04-30",
      "dateFormatted": "26.04 – 30.04.2027",
      "title": "Весняний виїзний (екскурсійний) тиждень ліцею 🚌🌸",
      "titlePl": "Wiosenny tydzień wyjazdowy / wycieczkowy",
      "category": "trip",
      "categoryName": "Виїзди та екскурсії",
      "time": "Весь тиждень",
      "description": "Весняний тиждень виїзних освітніх програм, екскурсій містами Польщі та природоохоронними парками.",
      "grade1Note": "Виїзні активності для учнів 1-х класів.",
      "location": "Виїзні маршрути"
    },
    {
      "id": "ev-may-1-labor",
      "date": "2027-05-01",
      "dateFormatted": "01.05.2027 (Субота)",
      "title": "Свято Праці 🛑",
      "titlePl": "Święto Pracy",
      "category": "holiday",
      "categoryName": "Державне свято",
      "time": "Весь день",
      "description": "Державне свято та вихідний день.",
      "grade1Note": "Вихідний день.",
      "location": "Польща"
    },
    {
      "id": "ev-may-3-const",
      "date": "2027-05-03",
      "dateFormatted": "03.05.2027 (Понеділок)",
      "title": "Свято Національної Конституції 3 Травня 🇵🇱🛑",
      "titlePl": "Święto Narodowe Trzeciego Maja",
      "category": "holiday",
      "categoryName": "Державне свято",
      "time": "Весь день",
      "description": "Державне свято Польщі, офіційний вихідний день.",
      "grade1Note": "Вихідний день.",
      "location": "Польща"
    },
    {
      "id": "ev-may-matura-off",
      "date": "2027-05-04",
      "endDate": "2027-05-07",
      "dateFormatted": "04.05 – 07.05.2027 (Вівторок – П'ятниця)",
      "title": "Вільні від уроків дні для 1-х класів (Період Матури 4-х кл.) 🛑🎓",
      "titlePl": "Dni wolne od zajęć dydaktycznych (Pisemne egzaminy maturalne)",
      "category": "off",
      "categoryName": "Вільні дні",
      "time": "4 дні",
      "description": "У ці дні у приміщеннях ліцею проходять обов'язкові письмові іспити на атестат зрілості (Матура) для випускників 4-х класів. Згідно із розпорядженням дирекції, для учнів 1-х, 2-х та 3-х класів навчальні заняття скасовані!",
      "grade1Note": "ВЕЛИКИЙ БОНУС ДЛЯ 1-Х КЛАСІВ: 4 повних дні без занять (разом із 3 травня — 9 днів весняного відпочинку поспіль)!",
      "location": "Ліцей зайнятий екзаменами"
    },
    {
      "id": "ev-may-27-corpus",
      "date": "2027-05-27",
      "dateFormatted": "27.05.2027 (Четвер)",
      "title": "Свято Тіла і Крові Христових (Boże Ciało) 🌿🛑",
      "titlePl": "Uroczystość Najświętszego Ciała i Krwi Chrystusa (Boże Ciało)",
      "category": "holiday",
      "categoryName": "Державне свято",
      "time": "Весь день",
      "description": "Державне та релігійне свято, офіційний вихідний день у всій Польщі.",
      "grade1Note": "Вихідний день.",
      "location": "Польща"
    },
    {
      "id": "ev-may-28-longwknd",
      "date": "2027-05-28",
      "dateFormatted": "28.05.2027 (П'ятниця)",
      "title": "Вільний від уроків день (Директорський довгий вікенд) 🛑☀️",
      "titlePl": "Dodatkowy dzień wolny od zajęć dydaktycznych",
      "category": "off",
      "categoryName": "Вільні дні",
      "time": "Весь день",
      "description": "Директорський вихідний день між Божим Тілом та вихідними. Утворюється 4-денний вікенд (27–30 травня).",
      "grade1Note": "Вільний від уроків день для 1-х класів.",
      "location": "Ліцей"
    },
    {
      "id": "ev-jun-1-grade",
      "date": "2027-06-01",
      "dateFormatted": "До 01.06.2027 (Вівторок)",
      "title": "Попередження про річні оцінки в електронному щоденнику ⚠️",
      "titlePl": "Poinformowanie o przewidywanych ocenach rocznych i zagrożeniach",
      "category": "grade",
      "categoryName": "Оцінювання",
      "time": "Дедлайн",
      "description": "Вчителі вносять до системи Librus орієнтовні річні бали та загрози незадовільних оцінок з предметів і поведінки.",
      "grade1Note": "Батькам необхідно перевірити прогнозовані річні оцінки в системі.",
      "location": "Librus"
    },
    {
      "id": "ev-jun-1-meeting",
      "date": "2027-06-01",
      "dateFormatted": "01.06.2027 (Вівторок)",
      "title": "Батьківські збори: прогнозовані річні оцінки 👥",
      "titlePl": "Zebranie z rodzicami: przewidywane oceny roczne",
      "category": "meeting",
      "categoryName": "Батьківські збори",
      "time": "17:30",
      "description": "Останні регулярні батьківські збори навчального року: обговорення річних результатів, процедури покращення балів.",
      "grade1Note": "Фінальні батьківські збори першого навчального року в ліцеї.",
      "location": "Кабінети ліцею"
    },
    {
      "id": "ev-jun-18-finalgrade",
      "date": "2027-06-18",
      "dateFormatted": "До 18.06.2027 (П'ятниця)",
      "title": "Дедлайн остаточного виставлення річних оцінок 📝",
      "titlePl": "Ostateczne wystawienie ocen rocznych (klasy 1, 2, 3)",
      "category": "grade",
      "categoryName": "Оцінювання",
      "time": "Дедлайн",
      "description": "Журнали оцінювання закриваються. Усі річні оцінки зафіксовані остаточно.",
      "grade1Note": "Фінальні річні оцінки 1-х класів.",
      "location": "Librus"
    },
    {
      "id": "ev-jun-22-council",
      "date": "2027-06-22",
      "dateFormatted": "22.06.2027 (Вівторок)",
      "title": "Класифікаційна педагогічна рада 1-х класів 📋",
      "titlePl": "Klasyfikacyjna rada pedagogiczna (klasy 1)",
      "category": "council",
      "categoryName": "Педагогічна рада",
      "time": "15:00",
      "description": "Офіційне затвердження переведення учнів 1-х класів до 2-го класу ліцею.",
      "grade1Note": "Переведення першокласників до 2-го класу ліцею!",
      "location": "Учительська"
    },
    {
      "id": "ev-jun-24-council",
      "date": "2027-06-24",
      "dateFormatted": "24.06.2027 (Четвер)",
      "title": "Підсумкова педагогічна рада ліцею за весь рік 🏛️",
      "titlePl": "Podsumowująca rada pedagogiczna",
      "category": "council",
      "categoryName": "Педагогічна рада",
      "time": "15:00",
      "description": "Підбиття загальних підсумків 2026/2027 навчального року в ліцеї.",
      "grade1Note": "Педагогічна рада вчителів ліцею.",
      "location": "Актова зала"
    },
    {
      "id": "ev-jun-25-triumph",
      "date": "2027-06-25",
      "dateFormatted": "25.06.2027 (П'ятниця)",
      "title": "Урочисте завершення навчального року для 1-х класів! 🎉🏆",
      "titlePl": "Uroczyste zakończenie roku szkolnego 2026/2027",
      "category": "triumph",
      "categoryName": "Закінчення року",
      "time": "10:00",
      "description": "Урочисте вручення свідоцтв, нагородження відмінників та активістів, святкова лінійка та перехід до 2-го класу ліцею!",
      "grade1Note": "Грандіозний фінал першого навчального року в ліцеї! Вітаємо першокласників із переходом у 2-й клас!",
      "location": "LXXVIII LO w Warszawie"
    },
    {
      "id": "ev-jun-26-vacation",
      "date": "2027-06-26",
      "endDate": "2027-08-31",
      "dateFormatted": "26.06 – 31.08.2027",
      "title": "Літні канікули (Ferie letnie) 🏖️🌊☀️",
      "titlePl": "Ferie letnie (Wakacje szkolne)",
      "category": "vacation",
      "categoryName": "Канікули",
      "time": "Понад 2 місяці",
      "description": "Заслужений літній відпочинок тривалістю понад два місяці.",
      "grade1Note": "Повні літні канікули до 31 серпня 2027 року.",
      "location": "Відпочинок"
    },
    {
      "id": "ev-aug-15-army",
      "date": "2027-08-15",
      "dateFormatted": "15.08.2027 (Неділя)",
      "title": "Свято Війська Польського та Успіння Богородиці 🇵🇱🛑",
      "titlePl": "Święto Wojska Polskiego i Wniebowzięcie NMP",
      "category": "holiday",
      "categoryName": "Державне свято",
      "time": "Весь день",
      "description": "Державне та релігійне свято Польщі.",
      "grade1Note": "Державне свято в період канікул.",
      "location": "Польща"
    }
  ]
};
